# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'courseGui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1485, 800)
        Form.setMinimumSize(QtCore.QSize(1485, 800))
        Form.setMaximumSize(QtCore.QSize(1485, 800))
        self.back_Button = QtWidgets.QPushButton(Form)
        self.back_Button.setGeometry(QtCore.QRect(30, 20, 93, 28))
        self.back_Button.setObjectName("back_Button")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(170, 50, 1141, 201))
        self.frame.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.courseName_label = QtWidgets.QLabel(self.frame)
        self.courseName_label.setGeometry(QtCore.QRect(430, 10, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.courseName_label.setFont(font)
        self.courseName_label.setObjectName("courseName_label")
        self.buyCourse_button = QtWidgets.QPushButton(self.frame)
        self.buyCourse_button.setGeometry(QtCore.QRect(990, 150, 141, 41))
        self.buyCourse_button.setStyleSheet("background-color: rgb(147, 147, 147);")
        self.buyCourse_button.setObjectName("buyCourse_button")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(430, 50, 190, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.coursePrice_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.coursePrice_label.setFont(font)
        self.coursePrice_label.setObjectName("coursePrice_label")
        self.horizontalLayout.addWidget(self.coursePrice_label)
        self.courseViedo_button = QtWidgets.QPushButton(self.frame)
        self.courseViedo_button.setGeometry(QtCore.QRect(20, 10, 401, 181))
        self.courseViedo_button.setObjectName("courseViedo_button")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(170, 260, 861, 501))
        self.tabWidget.setObjectName("tabWidget")
        self.intro_TabWidget = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(9)
        self.intro_TabWidget.setFont(font)
        self.intro_TabWidget.setObjectName("intro_TabWidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.intro_TabWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 240, 841, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMaximumSize(QtCore.QSize(1666, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setScaledContents(False)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.intro_TabWidget)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 821, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("TestImage_1.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.intro_TabWidget, "")
        self.comment_Tabwidget = QtWidgets.QWidget()
        self.comment_Tabwidget.setObjectName("comment_Tabwidget")
        self.comment_lineEdit = QtWidgets.QLineEdit(self.comment_Tabwidget)
        self.comment_lineEdit.setGeometry(QtCore.QRect(530, 310, 321, 81))
        self.comment_lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.comment_lineEdit.setObjectName("comment_lineEdit")
        self.sendMessage_button = QtWidgets.QPushButton(self.comment_Tabwidget)
        self.sendMessage_button.setGeometry(QtCore.QRect(740, 410, 111, 41))
        self.sendMessage_button.setObjectName("sendMessage_button")
        self.scrollArea = QtWidgets.QScrollArea(self.comment_Tabwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 491, 451))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 468, 697))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(446, 100))
        self.label.setMaximumSize(QtCore.QSize(446, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("TestImage_1.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(446, 100))
        self.label_12.setMaximumSize(QtCore.QSize(446, 100))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("TestImage_1.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(446, 100))
        self.label_16.setMaximumSize(QtCore.QSize(446, 100))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("TestImage_1.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(446, 100))
        self.label_15.setMaximumSize(QtCore.QSize(446, 100))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("TestImage_1.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_3.addWidget(self.label_15)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(446, 100))
        self.label_13.setMaximumSize(QtCore.QSize(446, 100))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("TestImage_1.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(446, 100))
        self.label_14.setMaximumSize(QtCore.QSize(446, 100))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("TestImage_1.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.comment_Tabwidget, "")
        self.source_Tabwidget = QtWidgets.QWidget()
        self.source_Tabwidget.setObjectName("source_Tabwidget")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.source_Tabwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(30, 10, 811, 441))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 809, 439))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setSpacing(20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 70))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("用户头像.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(45, 45))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget.addTab(self.source_Tabwidget, "")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(1080, 280, 231, 181))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 221, 154))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(5)
        self.line.setMidLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.teacherImage_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.teacherImage_label.setMinimumSize(QtCore.QSize(100, 100))
        self.teacherImage_label.setMaximumSize(QtCore.QSize(100, 100))
        self.teacherImage_label.setText("")
        self.teacherImage_label.setPixmap(QtGui.QPixmap("老师头像.jpg"))
        self.teacherImage_label.setScaledContents(True)
        self.teacherImage_label.setObjectName("teacherImage_label")
        self.horizontalLayout_2.addWidget(self.teacherImage_label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.teacherName_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.teacherName_label.setMaximumSize(QtCore.QSize(16666, 16666))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.teacherName_label.setFont(font)
        self.teacherName_label.setAlignment(QtCore.Qt.AlignCenter)
        self.teacherName_label.setObjectName("teacherName_label")
        self.verticalLayout_2.addWidget(self.teacherName_label)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.back_Button.setText(_translate("Form", "返回首页"))
        self.courseName_label.setText(_translate("Form", "Unity2D官方案例"))
        self.buyCourse_button.setText(_translate("Form", "购买课程"))
        self.label_3.setText(_translate("Form", "价格:"))
        self.coursePrice_label.setText(_translate("Form", "450元"))
        self.courseViedo_button.setText(_translate("Form", "PushButton"))
        self.label_9.setText(_translate("Form", "课程介绍"))
        self.label_10.setText(_translate("Form", "      本套教学使用Unity2019轻量级渲染管线，针对手机制作合适的地形编辑流程，同样适合制作开放世界的扩展方案。使用到Substance Designer，Zbrush，Maya，PS来辅助完成模型贴图部分。材质部分将主要讲解水和互动草的Shader制作，利用GPU的特性来快速实例像赛尔达一样的草坪。使用Houdini来制作树的叶子，给物件做LOD。在整个案列中每一个物件都会讲到如何快速制作和优化，分享作为最终关卡的完成者如何和你的上下游进行沟通。"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.intro_TabWidget), _translate("Form", "Tab 1"))
        self.comment_lineEdit.setText(_translate("Form", "发送你的评论...."))
        self.sendMessage_button.setText(_translate("Form", "发送消息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.comment_Tabwidget), _translate("Form", "Tab 2"))
        self.pushButton.setText(_translate("Form", "资源_1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.source_Tabwidget), _translate("Form", "页"))
        self.label_5.setText(_translate("Form", "授课老师"))
        self.teacherName_label.setText(_translate("Form", "伍老师"))
